@hostname = localhost
@port = 8800
@object = article
@host = {{hostname}}:{{port}}
@endpoint = api/v1/private/{{object}}
@endpointpublic = api/v1/public/{{object}}
@contentType = application/json

### Get All article
GET http://{{host}}/{{endpointpublic}}/getall HTTP/1.1
Content-Type: {{contentType}}

### Get article By Id
GET http://{{host}}/{{endpoint}}/getbyid?article_id=3 HTTP/1.1
Content-Type: {{contentType}}

### Create article
POST http://{{host}}/{{endpointpublic}}/create HTTP/1.1
Content-Type: {{contentType}}

{
     
      "article_title": "Công nghê mới năm 2024",
      "article_description": "Mở nguồn cảm hứng cho giới trẻ có đam mê nghệ thuật",
      "article_content": "Nội dung chi tiết về thông tin...",
      "article_slug": "bai-viet-mau-ve-du-lich-da-lat",
      "published_at": "2024-11-04T21:00:00.000Z",  
      "is_priority": 1,  
      "article_type_id": 1,  
      "employee_id": 1,  
      "thumbnail_img": "https://example.com/images/dalat.jpg",  
      "thumbnail_img_public_id": "articles/dalat-123" 
}

### Update 
PUT http://{{host}}/{{endpointpublic}}/update?article_id=7 HTTP/1.1
Content-Type: {{contentType}}

{
      "article_title": "Công nghê mới năm 2024",
      "article_description": "Mở nguồn cảm hứng cho giới trẻ có đam mê nghệ thuật",
      "article_content": "Nội dung chi tiết về thông tin...",
      "article_slug": "bai-viet-mau-ve-du-lich-da-lat",
      "published_at": "2024-11-04T21:00:00.000Z",  
      "is_priority": 0,  
      "article_type_id": 1,  
      "employee_id": 1,  
      "thumbnail_img": "https://example.com/images/dalat.jpg",  
      "thumbnail_img_public_id": "articles/dalat-123" 
}
### Delete 
DELETE http://{{host}}/{{endpoint}}/delete?article_id=6 HTTP/1.1
Content-Type: {{contentType}}

### Get Deleted All
GET http://{{host}}/{{endpoint}}/getalldeleted HTTP/1.1
Content-Type: {{contentType}}

