   @hostname = localhost
@port = 8800
@object = officeimage
@host = {{hostname}}:{{port}}
@endpoint = api/v1/private/{{object}}
@contentType = application/json
### Create Office Image
POST http://{{host}}/{{endpoint}}/create
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="officeId"

12
--MfnBoundry
Content-Disposition: form-data; name="images"; filename="Screenshot 2024-11-02 104534.png"
Content-Type: image/jpeg

< C:\Users\VanPhu\Pictures\Screenshots\Screenshot 2024-11-02 104534.png

--MfnBoundry
Content-Disposition: form-data; name="images"; filename="Screenshot 2024-11-01 133333.png"
Content-Type: image/jpeg

< C:\Users\VanPhu\Pictures\Screenshots\Screenshot 2024-11-01 133333.png

--MfnBoundry--