@hostname = localhost
@port = 8800
@object = office
@host = {{hostname}}:{{port}}
@endpoint = api/v1/private/{{object}}
@contentType = application/json

### Get All Office
GET http://{{host}}/{{endpoint}}/getall HTTP/1.1
Content-Type: {{contentType}}

### Get Office By Id
GET http://{{host}}/{{endpoint}}/getbyid?officeId=14422 HTTP/1.1
Content-Type: {{contentType}}

### Get Deleted Office
GET http://{{host}}/{{endpoint}}/getalldeleted HTTP/1.1
Content-Type: {{contentType}}

### Create Office
POST http://{{host}}/{{endpoint}}/create HTTP/1.1
Content-Type: {{contentType}}

{
   "name": "Central Offices 11",
   "address": "456 Central Ave, Suite 100, New York, NY 10001",
   "phone": "0323393511",
   "fax": "0323393511",
   "description": "Central office located in the heart of New York City.",
   "latitude": 40.712776,
   "longitude": -74.005974,
   "map_url": "https://maps.google.com/?q=40.712776,-74.005974"
}

### Update Office
PUT http://{{host}}/{{endpoint}}/update HTTP/1.1
Content-Type: {{contentType}}

{
   "officeId": 53,
   "name": "Downtown Office",
   "address": "789 Downtown Blvd, Suite 200, Los Angeles, CA 90001",
   "phone": "3105556789",
   "fax": "3105559876",
   "description": "Downtown office located in the heart of Los Angeles.",
   "latitude": 34.052235,
   "longitude": -118.243683,
   "map_url": "https://maps.google.com/?q=34.052235,-118.243683"
}

### Delete Office
DELETE http://{{host}}/{{endpoint}}/delete?officeId=64 HTTP/1.1
Content-Type: {{contentType}}

