@hostname = localhost
@port = 8800
@object = provinces
@host = {{hostname}}:{{port}}
@endpoint = api/v1/public/{{object}}
@contentType = application/json

### Get All Province
GET http://{{host}}/{{endpoint}}/getall HTTP/1.1
Content-Type: {{contentType}}

### Get Province By Id
GET http://{{host}}/{{endpoint}}/getbyid/27 HTTP/1.1