@hostname = localhost
@port = 8800
@object = review
@host = {{hostname}}:{{port}}
@endpoint = api/v1/private/{{object}}
@endpointPublic = api/v1/public/{{object}}
@contentType = application/json

### Get All Office 
GET http://{{host}}/{{endpointPublic}}/getall HTTP/1.1
Content-Type: {{contentType}}