   @hostname = localhost
@port = 8800
@object = way
@host = {{hostname}}:{{port}}
@endpoint = api/v1/private/{{object}}
@contentType = application/json

### Get All Way
GET http://{{host}}/{{endpoint}}/getall HTTP/1.1
Content-Type: {{contentType}}

### Get Way By Id
GET http://{{host}}/{{endpoint}}/getbyid?wayId=13 HTTP/1.1
Content-Type: {{contentType}}

### Create Way
POST http://{{host}}/{{endpoint}}/create HTTP/1.1
Content-Type: {{contentType}}

{
   "name": "Tuyến 11: Main Office 5 - Main Office 8", 
   "description": "Tuyến xe từ Main Office 5 đến Main Office 8"
}

### Update Way
PUT http://{{host}}/{{endpoint}}/update HTTP/1.1
Content-Type: {{contentType}}

{
   "wayId": 14,
   "name": "Tuyến 11: Main Office 5- Main Office 8", 
   "description": "Tuyến xe từ Main Office 5 đến Main Office 8"
}

### Delete Way
DELETE http://{{host}}/{{endpoint}}/delete?wayId=19 HTTP/1.1
Content-Type: {{contentType}}

### Get Deleted Way
GET http://{{host}}/{{endpoint}}/getalldeleted HTTP/1.1
Content-Type: {{contentType}}
